# Generated by Django 6.0.7 on 2026-07-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Resource name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('calculator', 'Calculator'), ('guide', 'Step-by-step guide'), ('glossary', 'Glossary of terms')], default='guide', max_length=20, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Short description')),
                ('content', models.TextField(blank=True, verbose_name='Full text / HTML / Instruction')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Link to external tool/calculator')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/files/', verbose_name='File (e.g. PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['category', 'title'],
            },
        ),
    ]
